import assert from 'node:assert/strict';
import { mkdir, mkdtemp, readFile, rm, symlink, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { spawn, spawnSync } from 'node:child_process';
import test from 'node:test';

const root = path.resolve(import.meta.dirname, '..');
test('chat UI exposes the GitHub Copilot device code outside transient status text', async () => {
  const [html, script, server, harness] = await Promise.all([
    readFile(path.join(root, 'src', 'public', 'index.html'), 'utf8'),
    readFile(path.join(root, 'src', 'public', 'app.js'), 'utf8'),
    readFile(path.join(root, 'src', 'server.js'), 'utf8'),
    readFile(path.join(root, 'src', 'pi-harness.mjs'), 'utf8'),
  ]);
  assert.match(html, /id="chat-copilot-login"/);
  assert.match(html, /id="chat-auth-code"/);
  assert.match(html, /id="chat-auth-dialog-code"/);
  assert.match(html, /id="todo-popover"/);
  assert.match(html, /id="chat-process-dirty"/);
  assert.match(script, /showAuthenticationCode\(provider, label, data\.user_code\)/);
  assert.match(script, /chatUi\.authDialog\.showModal\(\)/);
  assert.match(script, /Loading workspace…/);
  assert.match(script, /Loading chat history…/);
  assert.match(script, /while \(i < lines\.length && lines\[i\]\.trim\(\) && !blockBoundary\(lines\[i\]\)\)/);
  assert.match(script, /'~': \{ name: 'In progress'/);
  assert.match(script, /data-task-start-line/);
  assert.match(script, /function renderUserMarkdown\(element, content\)/);
  assert.match(script, /renderChatMarkdown\(element, content, '\/workspace\/index\.md'\)/);
  assert.match(script, /encodeURIComponent\(decodeURIComponent\(part\)\)/);
  assert.match(script, /Project pages/);
  assert.match(script, /Instructions', subtitle: 'System prompt'/);
  assert.match(script, /Activity', subtitle: 'Operation log'/);
  assert.match(script, /function projectLink\(item\)/);
  assert.match(script, /data-create-entry="page"/);
  assert.match(script, /data-create-entry="directory"/);
  assert.match(script, /pendingEntryRename/);
  assert.match(script, /form\.dataset\.saving = 'true'; pendingEntryRename = null; void loadPage\(\)/);
  assert.match(script, /class="nav-icon project-icon"/);
  assert.match(script, /function fileIcon\(path\)/);
  assert.match(script, /pptx: \['presentation', 'presentation'\]/);
  assert.match(script, /xlsx: \['spreadsheet', 'spreadsheet'\]/);
  assert.match(html, /Check side effects with LLM/);
  assert.match(html, /id="todo-use-llm" type="checkbox" checked/);
  assert.match(script, /Briefly check this project for related side effects/);
  assert.match(html, /Changes detected, click to process/);
  assert.match(script, /initiator: 'system'/);
  assert.match(script, /function updateNewThreadAvailability\(\)/);
  assert.match(script, /if \(!force && chatThreadId && !chatThreadHasUserChat\)/);
  assert.match(script, /Discover and run relevant available project checks/);
  assert.match(script, /If you cannot resolve a reported error/);
  assert.match(server, /event\.userCode \|\| event\.user_code/);
  assert.match(server, /openai-codex\|github-copilot/);
  assert.match(server, /workspace-relative Markdown paths/);
  assert.match(server, /chat: discovered/);
  assert.match(server, /chat: loaded/);
  assert.match(server, /chat: checked Git status/);
  assert.match(harness, /workspace tool timed out/);
  assert.match(server, /path\.relative\(git\.repo, candidate\)/);
});
test('server serves an arbitrary bundle, redirects legacy routes, and rejects escaping symlinks', { skip: !process.env.OK_WORKBENCH_INTEGRATION }, async () => {
  const repository = await mkdtemp(path.join(tmpdir(), 'ok-workbench-server-'));
  const workspace = path.join(repository, 'workspace');
  const sibling = path.join(repository, 'sibling');
  const git = (...args) => { const result = spawnSync('git', args, { cwd: repository, encoding: 'utf8' }); assert.equal(result.status, 0, result.stderr); };
  git('init'); git('config', 'user.email', 'test@example.invalid'); git('config', 'user.name', 'Test');
  await mkdir(workspace); await mkdir(sibling); await mkdir(path.join(workspace, 'linked-project')); await mkdir(path.join(workspace, 'unlisted-project')); await mkdir(path.join(workspace, 'bare-project'));
  const outside = path.join(tmpdir(), `ok-workbench-outside-${process.pid}.md`);
  await writeFile(path.join(workspace, 'index.md'), '# Test workspace\n\n- [Linked project](linked-project/index.md)\n* [ ] Direct task\n');
  await writeFile(path.join(workspace, 'linked-project', 'index.md'), '# Linked project\n');
  await writeFile(path.join(workspace, 'linked-project', 'status.md'), '# Status\n'); await writeFile(path.join(workspace, 'linked-project', 'log.md'), '# Log\n');
  await writeFile(path.join(workspace, 'unlisted-project', 'index.md'), '# Unlisted project\n');
  await writeFile(path.join(workspace, 'unlisted-project', 'status.md'), '# Status\n'); await writeFile(path.join(workspace, 'unlisted-project', 'log.md'), '# Log\n');
  await writeFile(path.join(workspace, 'tracked.md'), 'before\n'); await writeFile(path.join(sibling, 'tracked.md'), 'before\n');
  await writeFile(outside, 'private\n');
  await symlink(outside, path.join(workspace, 'escape.md'));
  git('add', '.'); git('commit', '-m', 'baseline');
  const port = 38517;
  const child = spawn(process.execPath, [path.join(root, 'dist', 'server.js')], { env: { ...process.env, OKF_WORKSPACE_ROOT: workspace, PORT: String(port) } });
  try {
    await new Promise((resolve, reject) => { const timer = setTimeout(() => reject(new Error('server did not start')), 5000); child.stdout?.on('data', () => { clearTimeout(timer); resolve(); }); child.on('error', reject); child.on('exit', code => reject(new Error(`server exited ${code}`))); });
    const document = await fetch(`http://127.0.0.1:${port}/api/document?path=/workspace/index.md`);
    assert.equal(document.status, 200); assert.equal((await document.json()).title, 'Test workspace');
    const project = await fetch(`http://127.0.0.1:${port}/api/project?path=/workspace/`);
    const projectBody = await project.json(); assert.ok(projectBody.projects.some(item => item.name === 'linked-project' && item.path === '/workspace/linked-project')); assert.ok(projectBody.projects.some(item => item.name === 'unlisted-project' && item.path === '/workspace/unlisted-project')); assert.ok(projectBody.projects.some(item => item.name === 'bare-project' && item.path === '/workspace/bare-project'));
    const escaped = await fetch(`http://127.0.0.1:${port}/api/document?path=/workspace/escape.md`);
    assert.equal(escaped.status, 404);
    const dirtyPage = await fetch(`http://127.0.0.1:${port}/workspace/`); const dirtyCsrf = (await dirtyPage.text()).match(/name="ok-workbench-csrf" content="([^"]+)"/)?.[1]; assert.ok(dirtyCsrf);
    await writeFile(path.join(workspace, 'linked-project', 'brief.md'), '# Brief\n');
    await new Promise(resolve => setTimeout(resolve, 350));
    const dirty = await fetch(`http://127.0.0.1:${port}/api/projects/linked-project/dirty`); const dirtyBody = await dirty.json(); assert.equal(dirtyBody.dirty, true); assert.ok(dirtyBody.items.some(item => item.path === 'brief.md'));
    const processed = await fetch(`http://127.0.0.1:${port}/api/projects/linked-project/dirty`, { method: 'POST', headers: { 'x-ok-workbench-csrf': dirtyCsrf } }); assert.equal(processed.status, 200); assert.equal((await processed.json()).dirty, false);
    await writeFile(path.join(workspace, 'linked-project', 'follow-up.md'), '# Follow-up\n');
    await new Promise(resolve => setTimeout(resolve, 350));
    const accumulated = await fetch(`http://127.0.0.1:${port}/api/projects/linked-project/dirty`); const accumulatedBody = await accumulated.json(); assert.equal(accumulatedBody.dirty, true); assert.ok(accumulatedBody.items.some(item => item.path === 'follow-up.md'));
    const processedAgain = await fetch(`http://127.0.0.1:${port}/api/projects/linked-project/dirty`, { method: 'POST', headers: { 'x-ok-workbench-csrf': dirtyCsrf } }); assert.equal(processedAgain.status, 200); assert.equal((await processedAgain.json()).dirty, false);
    await writeFile(path.join(workspace, 'linked-project', 'retired.md'), '# Retired\n'); await writeFile(path.join(workspace, 'linked-project', 'index.md'), '# Linked project\n'); await writeFile(path.join(workspace, 'linked-project', 'status.md'), '# Status\n'); await writeFile(path.join(workspace, 'linked-project', 'log.md'), '# Log\n');
    await new Promise(resolve => setTimeout(resolve, 350));
    const settled = await fetch(`http://127.0.0.1:${port}/api/projects/linked-project/dirty`, { method: 'POST', headers: { 'x-ok-workbench-csrf': dirtyCsrf } }); assert.equal((await settled.json()).dirty, false);
    await rm(path.join(workspace, 'linked-project', 'retired.md')); await new Promise(resolve => setTimeout(resolve, 350));
    const deleted = await fetch(`http://127.0.0.1:${port}/api/projects/linked-project/dirty`); const deletedBody = await deleted.json(); assert.equal(deletedBody.dirty, true); assert.ok(deletedBody.items.some(item => item.kind === 'deleted' && item.path === 'retired.md (deleted)'));
    const legacy = await fetch(`http://127.0.0.1:${port}/agents/`, { redirect: 'manual' });
    assert.equal(legacy.status, 308); assert.equal(legacy.headers.get('location'), '/workspace/');
    await writeFile(path.join(workspace, 'tracked.md'), 'workspace edit\n');
    await writeFile(path.join(sibling, 'tracked.md'), 'sibling edit\n');
    const status = await fetch(`http://127.0.0.1:${port}/api/projects/workspace/git/status`);
    const statusBody = await status.json(); assert.ok(statusBody.files.some(file => /workspace\/tracked\.md$/.test(file.path))); assert.ok(statusBody.files.every(file => !file.path.includes('sibling/')));
    const diff = await fetch(`http://127.0.0.1:${port}/api/projects/workspace/git/diff?source=unstaged`);
    const diffBody = await diff.json(); assert.match(diffBody.patch, /workspace edit/); assert.doesNotMatch(diffBody.patch, /sibling edit/);
    const page = await fetch(`http://127.0.0.1:${port}/workspace/`); const csrf = (await page.text()).match(/name="ok-workbench-csrf" content="([^"]+)"/)?.[1]; assert.ok(csrf);
    const revert = await fetch(`http://127.0.0.1:${port}/api/projects/workspace/git/revert`, { method: 'POST', headers: { 'content-type': 'application/json', 'x-ok-workbench-csrf': csrf }, body: JSON.stringify({ token: diffBody.token }) });
    assert.equal(revert.status, 200); assert.equal(await readFile(path.join(workspace, 'tracked.md'), 'utf8'), 'before\n'); assert.equal(await readFile(path.join(sibling, 'tracked.md'), 'utf8'), 'sibling edit\n');
    const todo = await fetch(`http://127.0.0.1:${port}/api/projects/workspace/todos`, { method: 'POST', headers: { 'content-type': 'application/json', 'x-ok-workbench-csrf': csrf }, body: JSON.stringify({ path: '/workspace/index.md', startLine: 4, endLine: 4, original: '* [ ] Direct task', replacement: '* [x] Direct task' }) });
    assert.equal(todo.status, 200); assert.match(await readFile(path.join(workspace, 'index.md'), 'utf8'), /\* \[x\] Direct task/);
    const created = await fetch(`http://127.0.0.1:${port}/api/projects`, { method: 'POST', headers: { 'content-type': 'application/json', 'x-ok-workbench-csrf': csrf }, body: JSON.stringify({ id: 'new-project', title: 'New project', description: 'Created from the project dialog.' }) });
    assert.equal(created.status, 201); assert.deepEqual(await created.json(), { id: 'new-project', path: 'new-project', location: '/workspace/new-project', title: 'New project', description: 'Created from the project dialog.', structure: 'OKF 0.2 project template' });
    assert.match(await readFile(path.join(workspace, 'new-project', 'index.md'), 'utf8'), /description: "Created from the project dialog\."/);
    assert.match(await readFile(path.join(workspace, 'index.md'), 'utf8'), /\[New project\]\(new-project\/\)/);
    const untitledPage = await fetch(`http://127.0.0.1:${port}/api/projects/new-project/entries`, { method: 'POST', headers: { 'content-type': 'application/json', 'x-ok-workbench-csrf': csrf }, body: JSON.stringify({ type: 'page', parentPath: '/workspace/new-project' }) });
    assert.equal(untitledPage.status, 201); const untitledPageBody = await untitledPage.json(); assert.equal(untitledPageBody.location, '/workspace/new-project/untitled-page.md'); assert.ok(untitledPageBody.renameToken);
    const renamedPage = await fetch(`http://127.0.0.1:${port}/api/projects/new-project/entries`, { method: 'PATCH', headers: { 'content-type': 'application/json', 'x-ok-workbench-csrf': csrf }, body: JSON.stringify({ path: untitledPageBody.location, name: 'Research notes', renameToken: untitledPageBody.renameToken }) });
    assert.equal(renamedPage.status, 200); assert.equal((await renamedPage.json()).location, '/workspace/new-project/research-notes.md');
    assert.match(await readFile(path.join(workspace, 'new-project', 'research-notes.md'), 'utf8'), /# Research notes/);
    const renamedExistingPage = await fetch(`http://127.0.0.1:${port}/api/projects/new-project/entries`, { method: 'PATCH', headers: { 'content-type': 'application/json', 'x-ok-workbench-csrf': csrf }, body: JSON.stringify({ path: '/workspace/new-project/research-notes.md', name: 'Collected research' }) });
    assert.equal(renamedExistingPage.status, 200); assert.equal((await renamedExistingPage.json()).location, '/workspace/new-project/collected-research.md');
    assert.match(await readFile(path.join(workspace, 'new-project', 'index.md'), 'utf8'), /\[Collected research\]\(collected-research\.md\)/);
    const untitledDirectory = await fetch(`http://127.0.0.1:${port}/api/projects/new-project/entries`, { method: 'POST', headers: { 'content-type': 'application/json', 'x-ok-workbench-csrf': csrf }, body: JSON.stringify({ type: 'directory', parentPath: '/workspace/new-project' }) });
    assert.equal(untitledDirectory.status, 201); const untitledDirectoryBody = await untitledDirectory.json();
    const renamedDirectory = await fetch(`http://127.0.0.1:${port}/api/projects/new-project/entries`, { method: 'PATCH', headers: { 'content-type': 'application/json', 'x-ok-workbench-csrf': csrf }, body: JSON.stringify({ path: untitledDirectoryBody.location, name: 'Reference material', renameToken: untitledDirectoryBody.renameToken }) });
    assert.equal(renamedDirectory.status, 200); assert.equal((await renamedDirectory.json()).location, '/workspace/new-project/reference-material');
    assert.match(await readFile(path.join(workspace, 'new-project', 'reference-material', 'index.md'), 'utf8'), /# Reference material/);
    assert.match(await readFile(path.join(workspace, 'new-project', 'index.md'), 'utf8'), /\[Reference material\]\(reference-material\/\)/);
    const renamedExistingDirectory = await fetch(`http://127.0.0.1:${port}/api/projects/new-project/entries`, { method: 'PATCH', headers: { 'content-type': 'application/json', 'x-ok-workbench-csrf': csrf }, body: JSON.stringify({ path: '/workspace/new-project/reference-material', name: 'Source material' }) });
    assert.equal(renamedExistingDirectory.status, 200); assert.equal((await renamedExistingDirectory.json()).location, '/workspace/new-project/source-material');
    const nestedPage = await fetch(`http://127.0.0.1:${port}/api/projects/new-project/entries`, { method: 'POST', headers: { 'content-type': 'application/json', 'x-ok-workbench-csrf': csrf }, body: JSON.stringify({ type: 'page', parentPath: '/workspace/new-project/source-material' }) });
    assert.equal(nestedPage.status, 201); assert.equal((await nestedPage.json()).location, '/workspace/new-project/source-material/untitled-page.md');
  } finally { child.kill(); }
});
